blueprint:
  name: Умное освещение
  description: >
    Включает свет при обнаружении движения, только если мастер-выключатель включён,
    уровень освещённости ниже заданного порога и есть движение.
    Свет выключается через заданный таймаут после прекращения движения
    или немедленно, если мастер-выключатель выключен.
  domain: automation
  source_url: https://github.com/e-l-l-a-r/ha-blueprints/SmartLighting.yaml
  input:
    master_switch:
      name: Мастер-выключатель (Опционально)
      description: Безусловно выключает свет (Оставьте пустым, если не используется)
      selector:
        entity:
          domain: binary_sensor
      #     multiple: false
      # default: ""
    illuminance_sensor:
      name: Датчик освещённости (Опционально)
      description: Сенсор освещённости (в люксах) (Оставьте пустым, если не используется)
      selector:
        entity:
          domain: sensor
    illuminance_threshold:
      name: Порог освещённости (люкс)
      description: Свет включается только если освещённость ниже этого значения
      selector:
        number:
          min: 0
          max: 300
          step: 1
          mode: box
      default: 50
    motion_sensor:
      name: Датчик присутствия
      description: Бинарный датчик движения
      selector:
        entity:
          domain: binary_sensor
    light_entities:
      name: Светильники
      description: Один или несколько светильников для управления
      selector:
        target:
          entity:
            domain: light
    motion_timeout:
      name: Таймаут отсутствия движения (секунды)
      description: Через сколько минут после окончания движения выключать свет
      selector:
        number:
          min: 1
          max: 300
          step: 1
          mode: box
      default: 15

mode: restart

trigger:
  # 1. Движение обнаружено
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
    id: "motion_on"

  # 2. Мастер-выключатель включён
  - platform: state
    alias: Мастер включен
    entity_id: !input master_switch
    to: "on"
    id: "master_on"

  # 3. Освещённость упала ниже порога
  - platform: numeric_state
    entity_id: !input illuminance_sensor
    below: !input illuminance_threshold
    id: "dark_enough"

  # 4. Мастер-выключатель выключен → выключить свет
  - platform: state
    entity_id: !input master_switch
    alias: Мастер выключен
    to: "off"
    id: "master_off"

variables:
  master_switch_condition: '{{ master_switch == none or (states[master_switch].state == "on" ) }}'
  illuminance_sensor_condition : '{{ illuminance_sensor == none or (states[illuminance_sensor].state < illuminance_threshold ) }}'

condition:
  - alias: "Мастер-выключатель включён и темно"
    condition: and
    conditions:
      - condition: state
        entity_id: !input master_switch
        state: "on"
      - condition: numeric_state
        entity_id: !input illuminance_sensor
        below: !input illuminance_threshold

# condition:
#   - alias: "Мастер-выключатель включён и темно"
#     condition: and
#     conditions:
#       - "{{ master_switch_condition }}"
#       - "{{ illuminance_sensor_condition }}"

action:
  # Обработка выключения при отключении мастера
  - if:
      - "{{ trigger.id == 'master_off' }}"
      alias: Триггер отключения мастера
        
    then:
      - alias: Выключаем свет
        service: light.turn_off
        target: !input light_entities
        continue_on_error: true
    else:
      - if:
          # Условие: мастер-выключатель либо не задан, либо включён
          # - "{{ master_switch_condition }}"
          # Движение есть
          - alias: Обнаружено присутствие
            condition: state
            entity_id: !input motion_sensor
            state: "on"
          # Темно
          # - "{{ illuminance_sensor_condition }}"
        then:
          - alias: Включаем свет
            service: light.turn_on
            target: !input light_entities
          - alias: Ждем прекращения движеиня
             wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                to: "off"
                for:
                  seconds: !input motion_timeout
          - alias: Отключаем свет
            service: light.turn_off
            target: !input light_entities
            continue_on_error: true
